"""Configuration loading for mergetrain.

mergetrain deliberately keeps runtime dependencies at zero. If PyYAML is
installed it is used; otherwise a small YAML subset parser handles the project
configuration shape generated by ``mergetrain init``.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from .errors import ConfigError

DEFAULT_CONFIG_NAME = ".mergetrain.yaml"

# Schema version of `.mergetrain.yaml` (issue #44). A file with no `version:`
# key is treated as version 1 (every file written before versioning existed).
# Mirrors store.SCHEMA_VERSION / registry.REGISTRY_VERSION: one integer per
# artifact, forward-only. Enforcement of a too-new config is command-scoped
# (the deploy/enqueue path fails closed; recovery and read-only commands stay
# permissive) — not done inside load_config, so a version mismatch after a
# rollback can never lock an operator out of crash recovery.
CONFIG_VERSION = 1
NOTIFY_TRANSITIONS = ("landed", "blocked", "needs_reconcile", "daemon_paused")


@dataclass(frozen=True, slots=True)
class ProjectConfig:
    name: str


@dataclass(frozen=True, slots=True)
class StateConfig:
    db: Path
    logs: Path
    worktree_root: Path


@dataclass(frozen=True, slots=True)
class GitConfig:
    remote: str = "origin"
    integration_branch: str = "main"
    push_refs: tuple[str, ...] = ("main",)

    @property
    def integration_ref(self) -> str:
        return f"{self.remote}/{self.integration_branch}"


@dataclass(frozen=True, slots=True)
class QueueConfig:
    lock_ttl_minutes: int = 30
    daemon_interval_seconds: int = 15
    heartbeat_interval_seconds: int = 10
    command_timeout_seconds: int = 3600


@dataclass(frozen=True, slots=True)
class AgentConfig:
    require_clean_worktree_before_enqueue: bool = True
    require_explicit_auto_approval: bool = True
    prefer_json_status: bool = True


@dataclass(frozen=True, slots=True)
class NotifyConfig:
    webhook_url: str = ""
    transitions: tuple[str, ...] = NOTIFY_TRANSITIONS
    timeout_seconds: int = 10

    def to_dict(self) -> dict[str, Any]:
        # A webhook commonly embeds a secret token. Observation surfaces only
        # reveal whether one is configured, never the credential-bearing URL.
        return {
            "webhook_configured": bool(self.webhook_url),
            "transitions": list(self.transitions),
            "timeout_seconds": self.timeout_seconds,
        }


@dataclass(frozen=True, slots=True)
class TerminologyConfig:
    """Human-facing words for the provider-neutral Git push operation."""

    git_operation: str = "deploy"

    @property
    def action(self) -> str:
        return self.git_operation

    @property
    def in_progress(self) -> str:
        return {
            "deploy": "deploying",
            "integrate": "integrating",
            "push": "pushing",
        }[self.git_operation]

    @property
    def completed(self) -> str:
        return {
            "deploy": "deployed",
            "integrate": "integrated",
            "push": "pushed",
        }[self.git_operation]

    @property
    def noun(self) -> str:
        return {
            "deploy": "deployment",
            "integrate": "integration",
            "push": "push",
        }[self.git_operation]

    def to_dict(self) -> dict[str, str]:
        return {
            "git_operation": self.git_operation,
            "action": self.action,
            "in_progress": self.in_progress,
            "completed": self.completed,
            "noun": self.noun,
        }


@dataclass(frozen=True, slots=True)
class GateConfig:
    name: str
    run: str
    always_rerun_on_deploy: bool = False


@dataclass(frozen=True, slots=True)
class ReuseConfig:
    enabled: bool = False
    max_age_minutes: int = 60
    on_mismatch: str = "rerun"
    fingerprints: tuple[GateConfig, ...] = ()


@dataclass(frozen=True, slots=True)
class DeployConfig:
    verify: tuple[GateConfig, ...] = ()
    reuse: ReuseConfig = ReuseConfig()


@dataclass(frozen=True, slots=True)
class MergetrainConfig:
    project: ProjectConfig
    state: StateConfig
    git: GitConfig
    queue: QueueConfig
    agent: AgentConfig
    terminology: TerminologyConfig
    gates: tuple[GateConfig, ...]
    deploy: DeployConfig
    repo: Path
    config_path: Path
    config_exists: bool
    notify: NotifyConfig = NotifyConfig()
    config_version: int = CONFIG_VERSION

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["state"] = {key: str(value) for key, value in data["state"].items()}
        data["repo"] = str(self.repo)
        data["config_path"] = str(self.config_path)
        data["git"]["integration_ref"] = self.git.integration_ref
        data["terminology"] = self.terminology.to_dict()
        data["notify"] = self.notify.to_dict()
        return data


def _strip_quotes(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _parse_scalar(value: str) -> Any:
    value = value.strip()
    lowered = value.lower()
    if value == "[]":
        return []
    if value == "{}":
        return {}
    if value.startswith(("[", "{")):
        raise ConfigError(
            "flow-style YAML collections are unsupported without PyYAML; "
            "use block-style lists or mappings"
        )
    if lowered in {"true", "false"}:
        return lowered == "true"
    if lowered in {"null", "none", "~"}:
        return None
    if value and value[0] in {'"', "'"}:
        return _strip_quotes(value)
    try:
        return int(value)
    except ValueError:
        return value


def _strip_inline_comment(line: str) -> str:
    """Drop a trailing ``# ...`` comment, matching PyYAML.

    A ``#`` starts a comment only at the start of the value or when preceded by
    whitespace, and never inside a quoted scalar — so ``key: value  # note`` is
    trimmed to ``key: value`` while ``url: http://x#frag`` and
    ``key: "a # b"`` are left intact. Leading indentation is preserved so the
    caller can still measure it. Without this the built-in (no-PyYAML) parser
    diverged from PyYAML and silently corrupted values like a gate ``name``.
    """

    in_single = in_double = False
    for i, ch in enumerate(line):
        if ch == "'" and not in_double:
            if in_single:
                in_single = False
            elif i == 0 or line[i - 1].isspace() or line[i - 1] in ":,[-":
                in_single = True
        elif ch == '"' and not in_single:
            if in_double:
                in_double = False
            elif i == 0 or line[i - 1].isspace() or line[i - 1] in ":,[-":
                in_double = True
        elif ch == "#" and not in_single and not in_double:
            if i == 0 or line[i - 1] in (" ", "\t"):
                return line[:i].rstrip()
    return line.rstrip()


_LEGACY_YAML_BOOLEAN = re.compile(r"^(?:yes|no|on|off)$", re.IGNORECASE)
_AMBIGUOUS_YAML_INTEGER = re.compile(
    r"^[+-]?(?:0[xX][0-9a-fA-F]+|0[bB][01]+|0[oO][0-7]+|0[0-9]+)$"
)


def _validate_yaml_text(text: str) -> None:
    """Reject constructs whose meaning changes with the optional YAML parser.

    The built-in parser is the zero-dependency default, so a config must either
    mean the same thing with PyYAML installed or fail before deploy settings are
    defaulted. Ambiguous scalars can still be used by quoting them explicitly.
    """

    for raw in text.splitlines():
        leading = raw[: len(raw) - len(raw.lstrip(" \t"))]
        if "\t" in leading:
            raise ConfigError("tab indentation is unsupported; use spaces")
        stripped = _strip_inline_comment(raw).strip()
        if not stripped:
            continue
        candidate = stripped[2:].strip() if stripped.startswith("- ") else stripped
        key, sep, value = candidate.partition(":")
        if sep and (not value or value[0].isspace()):
            candidate = value.strip()
        if not candidate or candidate.startswith(("'", '"', "[", "{")):
            continue
        if _LEGACY_YAML_BOOLEAN.fullmatch(candidate):
            raise ConfigError(
                "ambiguous YAML boolean; use true/false or quote it as a string"
            )
        if _AMBIGUOUS_YAML_INTEGER.fullmatch(candidate):
            raise ConfigError(
                "ambiguous YAML integer; use an unprefixed decimal value or quote it"
            )


def _clean_yaml_lines(text: str) -> list[tuple[int, str]]:
    cleaned: list[tuple[int, str]] = []
    for raw in text.splitlines():
        line = _strip_inline_comment(raw)
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        cleaned.append((indent, line.strip()))
    return cleaned


def _parse_simple_yaml(text: str) -> dict[str, Any]:
    _validate_yaml_text(text)
    lines = _clean_yaml_lines(text)

    def parse_block(index: int, indent: int) -> tuple[Any, int]:
        while index < len(lines) and lines[index][0] < indent:
            return {}, index
        if index >= len(lines):
            return {}, index
        if lines[index][0] == indent and lines[index][1].startswith("- "):
            return parse_list(index, indent)
        return parse_map(index, indent)

    def parse_map(index: int, indent: int) -> tuple[dict[str, Any], int]:
        result: dict[str, Any] = {}
        while index < len(lines):
            current_indent, stripped = lines[index]
            if current_indent < indent:
                break
            if current_indent > indent:
                raise ConfigError(f"unexpected indentation near: {stripped}")
            if stripped.startswith("- "):
                break
            key, sep, value = stripped.partition(":")
            if not sep:
                raise ConfigError(f"expected key: value near: {stripped}")
            key = key.strip()
            value = value.strip()
            index += 1
            if value:
                result[key] = _parse_scalar(value)
            else:
                if index < len(lines) and lines[index][0] > current_indent:
                    child, index = parse_block(index, lines[index][0])
                    result[key] = child
                else:
                    result[key] = None
        return result, index

    def parse_list(index: int, indent: int) -> tuple[list[Any], int]:
        result: list[Any] = []
        while index < len(lines):
            current_indent, stripped = lines[index]
            if current_indent < indent:
                break
            if current_indent != indent or not stripped.startswith("- "):
                break
            rest = stripped[2:].strip()
            index += 1
            if not rest:
                if index < len(lines) and lines[index][0] > current_indent:
                    child, index = parse_block(index, lines[index][0])
                    result.append(child)
                else:
                    result.append(None)
                continue
            # Common list-of-maps shape: ``- name: tests``.
            _key, _sep, _value = rest.partition(":")
            if (
                _sep
                and (not _value or _value[0].isspace())
                and not rest.startswith(("'", '"'))
            ):
                key, _, value = rest.partition(":")
                item: dict[str, Any] = {key.strip(): _parse_scalar(value.strip()) if value.strip() else None}
                if index < len(lines) and lines[index][0] > current_indent:
                    child, index = parse_map(index, lines[index][0])
                    item.update(child)
                result.append(item)
            else:
                result.append(_parse_scalar(rest))
        return result, index

    parsed, final_index = parse_block(0, 0)
    if final_index != len(lines):
        _, token = lines[final_index]
        raise ConfigError(f"could not parse config near: {token}")
    if not isinstance(parsed, dict):
        raise ConfigError("top-level YAML value must be a mapping")
    return parsed


def load_yaml(text: str) -> dict[str, Any]:
    _validate_yaml_text(text)
    try:
        import yaml  # type: ignore
    except Exception:
        return _parse_simple_yaml(text)
    try:
        loaded = yaml.safe_load(text) or {}
    except yaml.YAMLError as exc:
        raise ConfigError(f"invalid YAML: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ConfigError("top-level YAML value must be a mapping")
    return loaded


def default_config_dict(project_name: str = "example-app") -> dict[str, Any]:
    return {
        "version": CONFIG_VERSION,
        "project": {"name": project_name},
        "state": {
            "db": ".mergetrain/queue.sqlite",
            "logs": ".mergetrain/logs",
            "worktree_root": ".mergetrain/worktrees",
        },
        "git": {"remote": "origin", "integration_branch": "main", "push_refs": ["main"]},
        "queue": {
            "lock_ttl_minutes": 30,
            "daemon_interval_seconds": 15,
            "heartbeat_interval_seconds": 10,
            "command_timeout_seconds": 3600,
        },
        "agent": {
            "require_clean_worktree_before_enqueue": True,
            "require_explicit_auto_approval": True,
            "prefer_json_status": True,
        },
        "notify": {
            "webhook_url": "",
            "transitions": list(NOTIFY_TRANSITIONS),
            "timeout_seconds": 10,
        },
        "terminology": {"git_operation": "deploy"},
        "gates": [{"name": "diff-check", "run": "git diff --check ${integration_ref}..HEAD"}],
        "deploy": {"verify": []},
    }


def render_default_config(project_name: str = "example-app") -> str:
    return f"""version: {CONFIG_VERSION}

project:
  name: {project_name}

state:
  db: .mergetrain/queue.sqlite
  logs: .mergetrain/logs
  worktree_root: .mergetrain/worktrees

git:
  remote: origin
  integration_branch: main
  push_refs:
    - main

queue:
  lock_ttl_minutes: 30
  daemon_interval_seconds: 15
  heartbeat_interval_seconds: 10
  command_timeout_seconds: 3600

agent:
  require_clean_worktree_before_enqueue: true
  require_explicit_auto_approval: true
  prefer_json_status: true

notify:
  # Optional provider-neutral JSON webhook; this URL may contain a secret.
  webhook_url: ""
  transitions:
    - landed
    - blocked
    - needs_reconcile
    - daemon_paused
  timeout_seconds: 10

terminology:
  # Human-facing label only. Machine status remains `deployed`.
  git_operation: deploy

gates:
  - name: diff-check
    run: git diff --check ${{integration_ref}}..HEAD
  # Add service-specific checks here, for example:
  # - name: tests
  #   run: python -m unittest discover -s tests

deploy:
  verify: []
  reuse:
    enabled: false
    max_age_minutes: 60
    on_mismatch: rerun
    fingerprints: []
  # Add post-push checks here, for example:
  # verify:
  #   - name: live-health
  #     run: curl -fsS https://example.invalid/health
"""


def _as_mapping(data: dict[str, Any], key: str) -> dict[str, Any]:
    value = data.get(key, {})
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ConfigError(f"{key} must be a mapping")
    return value


def _as_gate_list(value: Any, *, key: str) -> tuple[GateConfig, ...]:
    if value in (None, {}):
        return ()
    if not isinstance(value, list):
        raise ConfigError(f"{key} must be a list")
    gates: list[GateConfig] = []
    for index, item in enumerate(value):
        if not isinstance(item, dict):
            raise ConfigError(f"{key}[{index}] must be a mapping")
        name_value = item.get("name", "")
        run_value = item.get("run", "")
        if not isinstance(name_value, str) or not isinstance(run_value, str):
            raise ConfigError(f"{key}[{index}] name and run must be strings")
        name = name_value.strip()
        run = run_value.strip()
        if not name or not run:
            raise ConfigError(f"{key}[{index}] requires name and run")
        always_rerun = item.get("always_rerun_on_deploy", False)
        if not isinstance(always_rerun, bool):
            raise ConfigError(
                f"{key}[{index}].always_rerun_on_deploy must be true or false"
            )
        gates.append(
            GateConfig(
                name=name,
                run=run,
                always_rerun_on_deploy=always_rerun,
            )
        )
    return tuple(gates)


def _nonempty_string(value: Any, *, key: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{key} must be a non-empty string")
    return value.strip()


def _push_refs(value: Any) -> tuple[str, ...]:
    items = [value] if isinstance(value, str) else value
    if not isinstance(items, list) or not items:
        raise ConfigError("git.push_refs must contain at least one ref")
    refs: list[str] = []
    for index, item in enumerate(items):
        refs.append(_nonempty_string(item, key=f"git.push_refs[{index}]"))
    if len(set(refs)) != len(refs):
        raise ConfigError("git.push_refs must not contain duplicates")
    return tuple(refs)


def _positive_int(value: Any, *, key: str) -> int:
    if isinstance(value, bool):
        raise ConfigError(f"{key} must be a positive integer")
    if isinstance(value, int):
        parsed = value
    elif isinstance(value, str) and value.strip().isdecimal():
        parsed = int(value.strip())
    else:
        raise ConfigError(f"{key} must be a positive integer")
    if parsed <= 0:
        raise ConfigError(f"{key} must be a positive integer")
    return parsed


def _boolean(value: Any, *, key: str) -> bool:
    if not isinstance(value, bool):
        raise ConfigError(f"{key} must be true or false")
    return value


def _resolve_path(repo: Path, value: Any, default: str, *, key: str) -> Path:
    if value is None:
        raw = default
    elif isinstance(value, (str, Path)):
        raw = str(value)
    else:
        raise ConfigError(f"{key} must be a path string")
    path = Path(raw).expanduser()
    if not path.is_absolute():
        path = repo / path
    return path.resolve()


def load_config(
    *,
    config_path: str | Path | None = None,
    repo: str | Path | None = None,
    db_override: str | Path | None = None,
) -> MergetrainConfig:
    repo_path = Path(repo or Path.cwd()).expanduser().resolve()
    path = Path(config_path).expanduser() if config_path else repo_path / DEFAULT_CONFIG_NAME
    if not path.is_absolute():
        path = (repo_path / path).resolve()
    exists = path.exists()
    if exists:
        data = load_yaml(path.read_text(encoding="utf-8"))
    else:
        data = default_config_dict(repo_path.name or "example-app")

    config_version, data = _read_config_version(data)

    project_data = _as_mapping(data, "project")
    project_name_value = project_data.get("name")
    project_name = (
        (repo_path.name or "example-app")
        if project_name_value is None
        else _nonempty_string(project_name_value, key="project.name")
    )

    state_data = _as_mapping(data, "state")
    db_value = db_override if db_override is not None else state_data.get("db")
    state = StateConfig(
        db=_resolve_path(
            repo_path, db_value, ".mergetrain/queue.sqlite", key="state.db"
        ),
        logs=_resolve_path(
            repo_path, state_data.get("logs"), ".mergetrain/logs", key="state.logs"
        ),
        worktree_root=_resolve_path(
            repo_path,
            state_data.get("worktree_root"),
            ".mergetrain/worktrees",
            key="state.worktree_root",
        ),
    )

    git_data = _as_mapping(data, "git")
    integration_branch = _nonempty_string(
        git_data.get("integration_branch", "main"), key="git.integration_branch"
    )
    push_refs = (
        _push_refs(git_data["push_refs"])
        if "push_refs" in git_data
        else (integration_branch,)
    )
    git = GitConfig(
        remote=_nonempty_string(git_data.get("remote", "origin"), key="git.remote"),
        integration_branch=integration_branch,
        push_refs=push_refs,
    )

    queue_data = _as_mapping(data, "queue")
    lock_ttl_minutes = _positive_int(
        queue_data.get("lock_ttl_minutes", 30), key="queue.lock_ttl_minutes"
    )
    heartbeat_interval_seconds = _positive_int(
        queue_data.get("heartbeat_interval_seconds", 10),
        key="queue.heartbeat_interval_seconds",
    )
    if heartbeat_interval_seconds >= lock_ttl_minutes * 60:
        raise ConfigError(
            "queue.heartbeat_interval_seconds must be shorter than queue.lock_ttl_minutes"
        )
    queue = QueueConfig(
        lock_ttl_minutes=lock_ttl_minutes,
        daemon_interval_seconds=_positive_int(
            queue_data.get("daemon_interval_seconds", 15),
            key="queue.daemon_interval_seconds",
        ),
        heartbeat_interval_seconds=heartbeat_interval_seconds,
        command_timeout_seconds=_positive_int(
            queue_data.get("command_timeout_seconds", 3600),
            key="queue.command_timeout_seconds",
        ),
    )

    agent_data = _as_mapping(data, "agent")
    agent = AgentConfig(
        require_clean_worktree_before_enqueue=bool(agent_data.get("require_clean_worktree_before_enqueue", True)),
        require_explicit_auto_approval=bool(agent_data.get("require_explicit_auto_approval", True)),
        prefer_json_status=bool(agent_data.get("prefer_json_status", True)),
    )

    notify_data = _as_mapping(data, "notify")
    webhook_value = notify_data.get("webhook_url", "")
    if webhook_value is None:
        webhook_url = ""
    elif isinstance(webhook_value, str):
        webhook_url = webhook_value.strip()
    else:
        raise ConfigError("notify.webhook_url must be a string")
    if webhook_url:
        parsed_webhook = urlsplit(webhook_url)
        if parsed_webhook.scheme not in {"http", "https"} or not parsed_webhook.hostname:
            raise ConfigError("notify.webhook_url must be an http or https URL")
    transitions_value = notify_data.get("transitions", list(NOTIFY_TRANSITIONS))
    if not isinstance(transitions_value, list):
        raise ConfigError("notify.transitions must be a list")
    transitions: list[str] = []
    for index, value in enumerate(transitions_value):
        transition = _nonempty_string(value, key=f"notify.transitions[{index}]")
        if transition not in NOTIFY_TRANSITIONS:
            allowed = ", ".join(NOTIFY_TRANSITIONS)
            raise ConfigError(
                f"notify.transitions[{index}] must be one of: {allowed}"
            )
        if transition not in transitions:
            transitions.append(transition)
    notify = NotifyConfig(
        webhook_url=webhook_url,
        transitions=tuple(transitions),
        timeout_seconds=_positive_int(
            notify_data.get("timeout_seconds", 10),
            key="notify.timeout_seconds",
        ),
    )

    terminology_data = _as_mapping(data, "terminology")
    git_operation = _nonempty_string(
        terminology_data.get("git_operation", "deploy"),
        key="terminology.git_operation",
    )
    if git_operation not in {"deploy", "integrate", "push"}:
        raise ConfigError(
            "terminology.git_operation must be 'deploy', 'integrate', or 'push'"
        )
    terminology = TerminologyConfig(git_operation=git_operation)

    deploy_data = _as_mapping(data, "deploy")
    reuse_value = deploy_data.get("reuse", {})
    if reuse_value is None:
        reuse_value = {}
    if not isinstance(reuse_value, dict):
        raise ConfigError("deploy.reuse must be a mapping")
    on_mismatch = str(reuse_value.get("on_mismatch", "rerun")).strip()
    if on_mismatch not in {"rerun", "fail"}:
        raise ConfigError("deploy.reuse.on_mismatch must be 'rerun' or 'fail'")
    fingerprints = _as_gate_list(
        reuse_value.get("fingerprints", []), key="deploy.reuse.fingerprints"
    )
    if any(item.always_rerun_on_deploy for item in fingerprints):
        raise ConfigError(
            "deploy.reuse.fingerprints do not support always_rerun_on_deploy"
        )
    deploy = DeployConfig(
        verify=_as_gate_list(deploy_data.get("verify", []), key="deploy.verify"),
        reuse=ReuseConfig(
            enabled=_boolean(
                reuse_value.get("enabled", False), key="deploy.reuse.enabled"
            ),
            max_age_minutes=_positive_int(
                reuse_value.get("max_age_minutes", 60),
                key="deploy.reuse.max_age_minutes",
            ),
            on_mismatch=on_mismatch,
            fingerprints=fingerprints,
        ),
    )
    gates = _as_gate_list(data.get("gates", []), key="gates")
    gate_names = [
        gate.name
        for gate in (*gates, *deploy.verify, *deploy.reuse.fingerprints)
    ]
    if len(set(gate_names)) != len(gate_names):
        raise ConfigError(
            "gate, deploy.verify, and deploy.reuse.fingerprint names must be unique"
        )

    return MergetrainConfig(
        project=ProjectConfig(name=project_name),
        state=state,
        git=git,
        queue=queue,
        agent=agent,
        notify=notify,
        terminology=terminology,
        gates=gates,
        deploy=deploy,
        repo=repo_path,
        config_path=path,
        config_exists=exists,
        config_version=config_version,
    )


def _read_config_version(data: dict[str, Any]) -> tuple[int, dict[str, Any]]:
    """Return ``(config_version, migrated_data)``.

    An absent ``version:`` key means version 1 — every config written before
    versioning existed rides forward unchanged. A newer version is *recorded*,
    not rejected here: refusal is command-scoped (the deploy path fails closed;
    recovery stays permissive), so load_config never blocks. Older versions are
    migrated forward in memory only; there is no persist path at v1 because
    re-serializing hand-edited YAML would lose comments and unknown keys.
    """

    raw = data.get("version", CONFIG_VERSION)
    if isinstance(raw, bool) or not isinstance(raw, int):
        raise ConfigError(
            f"config 'version' must be an integer, got {raw!r}"
        )
    if raw < 1:
        raise ConfigError(f"config 'version' must be >= 1, got {raw}")
    data = {key: value for key, value in data.items() if key != "version"}
    if raw < CONFIG_VERSION:
        data = _migrate_config(data, from_version=raw)
    return raw, data


def _migrate_config(data: dict[str, Any], *, from_version: int) -> dict[str, Any]:
    """Forward-migrate parsed config data in memory. Identity at v1 — the hook
    exists so a future v2 has a home without reshaping load_config."""

    return data
