"""Configuration loading for mergetrain.

mergetrain deliberately keeps runtime dependencies at zero. If PyYAML is
installed it is used; otherwise a small YAML subset parser handles the project
configuration shape generated by ``mergetrain init``.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable

from .errors import ConfigError

DEFAULT_CONFIG_NAME = ".mergetrain.yaml"


@dataclass(frozen=True, slots=True)
class ProjectConfig:
    name: str


@dataclass(frozen=True, slots=True)
class StateConfig:
    db: Path
    logs: Path
    worktree_root: Path


@dataclass(frozen=True, slots=True)
class GitConfig:
    remote: str = "origin"
    integration_branch: str = "main"
    push_refs: tuple[str, ...] = ("main",)

    @property
    def integration_ref(self) -> str:
        return f"{self.remote}/{self.integration_branch}"


@dataclass(frozen=True, slots=True)
class QueueConfig:
    lock_ttl_minutes: int = 30
    daemon_interval_seconds: int = 15


@dataclass(frozen=True, slots=True)
class AgentConfig:
    require_clean_worktree_before_enqueue: bool = True
    require_explicit_auto_approval: bool = True
    prefer_json_status: bool = True


@dataclass(frozen=True, slots=True)
class GateConfig:
    name: str
    run: str


@dataclass(frozen=True, slots=True)
class DeployConfig:
    verify: tuple[GateConfig, ...] = ()


@dataclass(frozen=True, slots=True)
class MergetrainConfig:
    project: ProjectConfig
    state: StateConfig
    git: GitConfig
    queue: QueueConfig
    agent: AgentConfig
    gates: tuple[GateConfig, ...]
    deploy: DeployConfig
    repo: Path
    config_path: Path
    config_exists: bool

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["state"] = {key: str(value) for key, value in data["state"].items()}
        data["repo"] = str(self.repo)
        data["config_path"] = str(self.config_path)
        data["git"]["integration_ref"] = self.git.integration_ref
        return data


def _strip_quotes(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _parse_scalar(value: str) -> Any:
    value = value.strip()
    lowered = value.lower()
    if value == "[]":
        return []
    if value == "{}":
        return {}
    if lowered in {"true", "false"}:
        return lowered == "true"
    if lowered in {"null", "none", "~"}:
        return None
    if value and value[0] in {'"', "'"}:
        return _strip_quotes(value)
    try:
        return int(value)
    except ValueError:
        return value


def _clean_yaml_lines(text: str) -> list[tuple[int, str]]:
    cleaned: list[tuple[int, str]] = []
    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        cleaned.append((indent, raw.strip()))
    return cleaned


def _parse_simple_yaml(text: str) -> dict[str, Any]:
    lines = _clean_yaml_lines(text)

    def parse_block(index: int, indent: int) -> tuple[Any, int]:
        while index < len(lines) and lines[index][0] < indent:
            return {}, index
        if index >= len(lines):
            return {}, index
        if lines[index][0] == indent and lines[index][1].startswith("- "):
            return parse_list(index, indent)
        return parse_map(index, indent)

    def parse_map(index: int, indent: int) -> tuple[dict[str, Any], int]:
        result: dict[str, Any] = {}
        while index < len(lines):
            current_indent, stripped = lines[index]
            if current_indent < indent:
                break
            if current_indent > indent:
                raise ConfigError(f"unexpected indentation near: {stripped}")
            if stripped.startswith("- "):
                break
            key, sep, value = stripped.partition(":")
            if not sep:
                raise ConfigError(f"expected key: value near: {stripped}")
            key = key.strip()
            value = value.strip()
            index += 1
            if value:
                result[key] = _parse_scalar(value)
            else:
                child, index = parse_block(index, indent + 2)
                result[key] = child
        return result, index

    def parse_list(index: int, indent: int) -> tuple[list[Any], int]:
        result: list[Any] = []
        while index < len(lines):
            current_indent, stripped = lines[index]
            if current_indent < indent:
                break
            if current_indent != indent or not stripped.startswith("- "):
                break
            rest = stripped[2:].strip()
            index += 1
            if not rest:
                child, index = parse_block(index, indent + 2)
                result.append(child)
                continue
            # Common list-of-maps shape: ``- name: tests``.
            if ":" in rest and not rest.startswith(("'", '"')):
                key, _, value = rest.partition(":")
                item: dict[str, Any] = {key.strip(): _parse_scalar(value.strip()) if value.strip() else None}
                if index < len(lines) and lines[index][0] >= indent + 2:
                    child, index = parse_map(index, indent + 2)
                    item.update(child)
                result.append(item)
            else:
                result.append(_parse_scalar(rest))
        return result, index

    parsed, final_index = parse_block(0, 0)
    if final_index != len(lines):
        _, token = lines[final_index]
        raise ConfigError(f"could not parse config near: {token}")
    if not isinstance(parsed, dict):
        raise ConfigError("top-level YAML value must be a mapping")
    return parsed


def load_yaml(text: str) -> dict[str, Any]:
    try:
        import yaml  # type: ignore
    except Exception:
        return _parse_simple_yaml(text)
    loaded = yaml.safe_load(text) or {}
    if not isinstance(loaded, dict):
        raise ConfigError("top-level YAML value must be a mapping")
    return loaded


def default_config_dict(project_name: str = "example-app") -> dict[str, Any]:
    return {
        "project": {"name": project_name},
        "state": {
            "db": ".mergetrain/queue.sqlite",
            "logs": ".mergetrain/logs",
            "worktree_root": ".mergetrain/worktrees",
        },
        "git": {"remote": "origin", "integration_branch": "main", "push_refs": ["main"]},
        "queue": {"lock_ttl_minutes": 30, "daemon_interval_seconds": 15},
        "agent": {
            "require_clean_worktree_before_enqueue": True,
            "require_explicit_auto_approval": True,
            "prefer_json_status": True,
        },
        "gates": [{"name": "diff-check", "run": "git diff --check ${integration_ref}..HEAD"}],
        "deploy": {"verify": []},
    }


def render_default_config(project_name: str = "example-app") -> str:
    return f"""project:
  name: {project_name}

state:
  db: .mergetrain/queue.sqlite
  logs: .mergetrain/logs
  worktree_root: .mergetrain/worktrees

git:
  remote: origin
  integration_branch: main
  push_refs:
    - main

queue:
  lock_ttl_minutes: 30
  daemon_interval_seconds: 15

agent:
  require_clean_worktree_before_enqueue: true
  require_explicit_auto_approval: true
  prefer_json_status: true

gates:
  - name: diff-check
    run: git diff --check ${{integration_ref}}..HEAD
  # Add service-specific checks here, for example:
  # - name: tests
  #   run: python -m unittest discover -s tests

deploy:
  verify: []
  # Add post-push checks here, for example:
  # verify:
  #   - name: live-health
  #     run: curl -fsS https://example.invalid/health
"""


def _as_mapping(data: dict[str, Any], key: str) -> dict[str, Any]:
    value = data.get(key, {})
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ConfigError(f"{key} must be a mapping")
    return value


def _as_gate_list(value: Any, *, key: str) -> tuple[GateConfig, ...]:
    if value in (None, {}):
        return ()
    if not isinstance(value, list):
        raise ConfigError(f"{key} must be a list")
    gates: list[GateConfig] = []
    for index, item in enumerate(value):
        if not isinstance(item, dict):
            raise ConfigError(f"{key}[{index}] must be a mapping")
        name = str(item.get("name", "")).strip()
        run = str(item.get("run", "")).strip()
        if not name or not run:
            raise ConfigError(f"{key}[{index}] requires name and run")
        gates.append(GateConfig(name=name, run=run))
    return tuple(gates)


def _tuple_of_str(value: Any, *, fallback: Iterable[str]) -> tuple[str, ...]:
    if value in (None, ""):
        return tuple(fallback)
    if isinstance(value, str):
        return (value,)
    if isinstance(value, list):
        return tuple(str(item) for item in value if str(item).strip())
    raise ConfigError("expected string or list of strings")


def _resolve_path(repo: Path, value: Any, default: str) -> Path:
    raw = str(value or default)
    path = Path(raw).expanduser()
    if not path.is_absolute():
        path = repo / path
    return path.resolve()


def load_config(
    *,
    config_path: str | Path | None = None,
    repo: str | Path | None = None,
    db_override: str | Path | None = None,
) -> MergetrainConfig:
    repo_path = Path(repo or Path.cwd()).expanduser().resolve()
    path = Path(config_path).expanduser() if config_path else repo_path / DEFAULT_CONFIG_NAME
    if not path.is_absolute():
        path = (repo_path / path).resolve()
    exists = path.exists()
    if exists:
        data = load_yaml(path.read_text(encoding="utf-8"))
    else:
        data = default_config_dict(repo_path.name or "example-app")

    project_data = _as_mapping(data, "project")
    project_name = str(project_data.get("name") or repo_path.name or "example-app")

    state_data = _as_mapping(data, "state")
    db_value = db_override if db_override is not None else state_data.get("db")
    state = StateConfig(
        db=_resolve_path(repo_path, db_value, ".mergetrain/queue.sqlite"),
        logs=_resolve_path(repo_path, state_data.get("logs"), ".mergetrain/logs"),
        worktree_root=_resolve_path(repo_path, state_data.get("worktree_root"), ".mergetrain/worktrees"),
    )

    git_data = _as_mapping(data, "git")
    integration_branch = str(git_data.get("integration_branch") or "main")
    push_refs = _tuple_of_str(git_data.get("push_refs"), fallback=(integration_branch,))
    if not push_refs:
        push_refs = (integration_branch,)
    git = GitConfig(
        remote=str(git_data.get("remote") or "origin"),
        integration_branch=integration_branch,
        push_refs=push_refs,
    )

    queue_data = _as_mapping(data, "queue")
    queue = QueueConfig(
        lock_ttl_minutes=int(queue_data.get("lock_ttl_minutes", 30)),
        daemon_interval_seconds=int(queue_data.get("daemon_interval_seconds", 15)),
    )

    agent_data = _as_mapping(data, "agent")
    agent = AgentConfig(
        require_clean_worktree_before_enqueue=bool(agent_data.get("require_clean_worktree_before_enqueue", True)),
        require_explicit_auto_approval=bool(agent_data.get("require_explicit_auto_approval", True)),
        prefer_json_status=bool(agent_data.get("prefer_json_status", True)),
    )

    deploy_data = _as_mapping(data, "deploy")
    deploy = DeployConfig(verify=_as_gate_list(deploy_data.get("verify", []), key="deploy.verify"))
    gates = _as_gate_list(data.get("gates", []), key="gates")

    return MergetrainConfig(
        project=ProjectConfig(name=project_name),
        state=state,
        git=git,
        queue=queue,
        agent=agent,
        gates=gates,
        deploy=deploy,
        repo=repo_path,
        config_path=path,
        config_exists=exists,
    )
